2 creating landing page
GSG-FC03/Education-App pull request #21
Opened 2021-08-06 16:07 UTC by malak119

[Land on first page](https://github.com/GSG-FC03/Education-App/issues/14)
- [x] Start with mobile first ```iphone X```
- [x] It should be ```responsive```
- [x] Add the logo of the website at the ```header```
- [x] Give the background of the page with color ```#E3F0FF```

- [x] Write the title/name of the website "Education Stage" with font (Questrial)

- [x] Write a text "Education Course Code" with font (Questrial), with opacity ```50%```.

- [x] Write the description of website " This app works as a collection of courses and challenging codes." with font (Questrial)
- [x] Create a button called "Let's Go !" which is used to move from landing page to the next page, with font (Questrial), and background color ```#1276D3```

2021-08-06 18:52 UTC, mo7mad4 commented on landingPage/style.css
> +
if you work `HOVER`, I think the button will be more beautiful
You can use this color  `#072F54`

2021-08-06 18:54 UTC, mo7mad4 requested changes
landing Page/style.css
Line 58
You can read it

2021-08-07 22:49 UTC, mo7mad4 approved these changes

2021-08-08 04:49 UTC, Sarah-Albalawi approved these changes

2021-08-08 06:47 UTC, sara219 approved these changes

2021-08-08 08:17 UTC, ferassmohana approved these changes

2021-08-08 08:20 UTC, Heba-Darabeh approved these changes

2021-08-08 09:03 UTC, merged