3 create signin page
GSG-FC03/Education-App pull request #25
Opened 2021-08-08 19:10 UTC by Heba-Darabeh

Still working on it.

2021-08-10 19:16 UTC, Sarah-Albalawi approved these changes

2021-08-11 09:33 UTC, malak119 approved these changes

2021-08-11 09:41 UTC, malak119 requested changes
Solve the conflict ..!

2021-08-11 11:26 UTC, ferassmohana approved these changes

2021-08-11 11:41 UTC, sara219 requested changes
The style needs to be modified
You have to make the elements in the centre of the page

![Screenshot from 2021-08-11 14-39-24](https://user-images.githubusercontent.com/47992412/129022661-b5a82e18-3745-4ca9-b86f-144c317b6ccc.png)

2021-08-11 11:47 UTC, Sarah-Albalawi approved these changes

2021-08-11 12:28 UTC, sara219 approved these changes

2021-08-11 12:40 UTC, mo7mad4 approved these changes

2021-08-11 12:41 UTC, merged